# Generated by Django 3.2.8 on 2021-11-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='credit',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
