# Generated by Django 3.2.8 on 2021-11-02 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='credit',
            field=models.URLField(default=django.utils.timezone.now, max_length=1024),
            preserve_default=False,
        ),
    ]
