# Generated by Django 3.2.8 on 2021-11-02 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_credit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categroies'},
        ),
    ]
