# Generated by Django 3.0.1 on 2021-12-07 14:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0009_auto_20211207_1402'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RateNreview',
            new_name='RateAndReview',
        ),
    ]
