# Generated by Django 3.0.1 on 2021-12-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20211208_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateandreview',
            name='title',
            field=models.CharField(choices=[(1, 'Bad'), (2, 'Normal'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=3, max_length=20),
        ),
    ]
