# Generated by Django 3.0.1 on 2021-12-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20211209_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateandreview',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
